version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db_1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_1
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
